export type PlayerId = string;

export interface Player {
  id: PlayerId;
  name: string;
  pushUsageCount: {
    front9: number; // OUT (1-9)
    back9: number;  // IN (10-18)
  };
}

export interface ScoreInput {
  score: number;
  isBirdie: boolean; // バーディー以上ならtrue
  usePush: boolean;  // このホールでプッシュ権を行使するか
}

export interface HoleResult {
  holeNumber: number; // 1-18
  par: number;
  scores: Record<PlayerId, ScoreInput>;

  // ペア分け情報
  teamA_Ids: [PlayerId, PlayerId];
  teamB_Ids: [PlayerId, PlayerId];

  // 計算用メタデータ
  carryOverMultiplier: number; // このホールに適用されるキャリーオーバー倍率 (通常1)
  isDraw: boolean; // 引き分けだった場合（次回へのキャリーオーバー発生フラグ）

  // 計算確定後のポイント変動 (誰が誰に何ポイント払う/貰うか)
  // プラスは受取、マイナスは支払
  pointsResult: Record<PlayerId, number>; // Points won/lost in this hole
  nextHoleMultiplier: number; // Multiplier for the NEXT hole generated by this result
}

export interface RoundResult {
  id: string; // UUID
  date: string; // ISO
  name: string; // Match Name
  players: Player[];
  history: HoleResult[];
  finalScores: Record<PlayerId, number>;
}

export interface GameState {
  players: Player[];
  currentHole: number;
  history: HoleResult[];

  // 設定
  settings: {
    rate: number; // 単位なし
    maxPushCountPerHalf: number; // デフォルト2
    language: 'en' | 'ja';
    matchName: string; // Added
  };

  // Saved Rounds
  savedRounds: RoundResult[];

  // 次のホールに持ち越されている倍率（初期値1, 引き分け発生で x2, x4...）
  nextHoleMultiplier: number;
}
